### ISSUE TITLE
Release to OSSRH staging repository

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/security-api#101]
- [ ] Uptake new Eclipse versions of dependencies (if any). Use [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) wiki to find components versions to use.

- [ ] Release to OSSRH staging repository

- [ ] Update [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) with released version number.

**Comment by m0mus** [comment]
Maxim is working on it.

**Comment by arjantijms** [comment]
@m0mus Just wondering, there was still some uncertainty about adding the nexus plug-ins to all poms individually, or waiting for the conversation to resolve and seeing if they get added to the master EE4J pom and then updating the master pom.

Is there any outcome yet?

**Comment by senivam** [comment]
Done:
https://oss.sonatype.org/content/groups/staging/jakarta/security/enterprise/jakarta.security.enterprise-api/1.0.1/

**Comment by m0mus** [comment]
@arjantijms There is no uncertainty. everything perfectly works and we just released it. You can take a look on the job to see how it's done. Also, I sent some details by email. If you have questions, me and @senivam at your service.

**Comment by arjantijms** [comment]
@m0mus I'll look for that email. The uncertainty I was referring to is this:

https://wiki.eclipse.org/EE4J_Maven_Publishing

Before when I did the staging (I staged for all projects) the resulting sonatype repo wasn't reachable. It would redirect me to the nexus login, and nobody had the credentials for that.

How did you got https://oss.sonatype.org/content/groups/staging/jakarta/security/enterprise/jakarta.security.enterprise-api/1.0.1/ to be reachable now?

Bill and Stuart mentioned having to add Nexus plug-ins to the pom, but I don't see these in the pom for this project.

**Comment by senivam** [comment]
@arjantijms that actually was my email and it was answering exactly your question. I will answer it here as well: 

Jobs are correct - they upload prepared artifact to staging. However after the job is done it is required to perform 2 more steps:

1. check what is uploaded using Nexus staging plugin:

Example of script:

export STAGING_CONFIG=${1}

export STAGING_PARAMS='-DnexusUrl=https://oss.sonatype.org/ -DserverId=ossrh'
export STAGING_PLUGIN='org.sonatype.plugins:nexus-staging-maven-plugin:1.6.7'


mvn -s ${STAGING_CONFIG} ${STAGING_PARAMS} ${STAGING_PLUGIN}:rc-list

after you will receive list of open (and closed) stagings and you can identify yours by <groupId>-<number>. 

The groupId is used without dots. Like jakartajaxws-1003

and the 2nd step is to close that open staging:

2. Closing script (using the same maven staging plugin):

export STAGING_DESC=${1}
export STAGING_REPO_ID=${2}
export STAGING_CONFIG=${3}

export STAGING_PARAMS='-DnexusUrl=https://oss.sonatype.org/ -DserverId=ossrh'
export STAGING_PLUGIN='org.sonatype.plugins:nexus-staging-maven-plugin:1.6.7'


mvn -s ${STAGING_CONFIG} ${STAGING_PARAMS} ${STAGING_PLUGIN}:rc-close -DstagingRepositoryId="${STAGING_REPO_ID}" -DstagingDescription="${STAGING_DESC}"

STAGING_REPO_ID is required identifier from previous step, 
STAGING_DESC is description of the staging taken from the dependencies image: https://wiki.eclipse.org/images/2/24/EE4J_projects_dependencies.png

STAGING_CONFIG is config file for maven (like settings.xml)

However if you do not find required staging in nexus using the 1st step you have to re-run release job (with OVERWRITE parameter checked) and perform those 2 steps after release job is done. Those 2 steps can be put in jenkins job and triggered after the release build is successful.
