### ISSUE TITLE
CTS failures

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/security-api#109]
95.35% failed tests. Please analyse.
https://jenkins.eclipse.org/jakartaee-tck/job/jakartaeetck-publish-reports/66/junit-reports-with-handlebars/test-summary/c6a59b3c-ec17-4db6-9152-9add01b709d8.html

**Comment by edbratt** [comment]
I'm not seeing that big a failure rate. Maybe I'm looking at the wrong 
thing (the server seems a bit unstable, I got a bunch of http 500 errors).

I see 89.74 passed, 9.75% failed. 0.51 skipped 
<https://jenkins.eclipse.org/jakartaee-tck/job/jakartaeetck-publish-reports/66/junit-reports-with-handlebars/testSuitesOverview.html>. 
(2123 failures) -- web services, sig-tests, securityapi, jaxrs, jaxrpc, 
ejb[timer&lite_tx&lite_singleton&lite_packaging]

**Comment by edbratt** [comment]
Sorry, please disregard. I was looking at all the tests, not just 
SecurityAPI.

**Comment by ggam** [comment]
Seems like deployment is failing on most of the tests. Can we see the server logs anywhere?

**Comment by ggam** [comment]
I'm able to build the standalone TCK bundle and pass all the tests (85 passed, 2 skipped). Attached are my results.

[report.zip](https://github.com/eclipse-ee4j/security-api/files/2658486/report.zip)

**Comment by anajosep** [comment]
@ggam Am getting failures against latest GF. 
JDK 8u171
GF build details:
Git Revision: 00e18e94d381aaa69f67b27d6ac599f335435026
Git Branch: EE4J_8
Build date: Fri Dec  7 04:46:41 UTC 2018

The logs are available here: https://jenkins.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck/branches/master/runs/152/nodes/86/steps/320/log/?start=0

**Comment by anajosep** [comment]
@ggam Am getting failures against latest GF. 
JDK 8u171
GF build details:
Git Revision: 00e18e94d381aaa69f67b27d6ac599f335435026
Git Branch: EE4J_8
Build date: Fri Dec  7 04:46:41 UTC 2018

The logs are available here: https://jenkins.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck/branches/master/runs/152/nodes/86/steps/320/log/?start=0

**Comment by ggam** [comment]
@anajosep I updated my local clone of the TCK and run with your shell scripts, which already download latest published GlassFish. I run the standalone test though, which might have different settings.

From your logs I see its complains about missing classes and warns about some class
```
[javatest.batch] Warning: incorrect classpath parameter: /home/jenkins/workspace/jakartaee-tck_master-M5QQ24N5SVVYX5KB3WEGZPMN4DNYF7IYAKOEXU5EKNOPHEJ3KEFA/glassfish5/glassfish/modules/javax.servlet-api.jar (/home/jenkins/workspace/jakartaee-tck_master-M5QQ24N5SVVYX5KB3WEGZPMN4DNYF7IYAKOEXU5EKNOPHEJ3KEFA/glassfish5/glassfish/modules/javax.servlet-api.jar (No such file or directory)). This directory or jar file will be ignored!
[javatest.batch] Warning: incorrect classpath parameter: /home/jenkins/workspace/jakartaee-tck_master-M5QQ24N5SVVYX5KB3WEGZPMN4DNYF7IYAKOEXU5EKNOPHEJ3KEFA/glassfish5/glassfish/modules/javax.security.enterprise-api.jar (/home/jenkins/workspace/jakartaee-tck_master-M5QQ24N5SVVYX5KB3WEGZPMN4DNYF7IYAKOEXU5EKNOPHEJ3KEFA/glassfish5/glassfish/modules/javax.security.enterprise-api.jar (No such file or directory)). This directory or jar file will be ignored!
[javatest.batch] Warning: incorrect classpath parameter: /home/jenkins/workspace/jakartaee-tck_master-M5QQ24N5SVVYX5KB3WEGZPMN4DNYF7IYAKOEXU5EKNOPHEJ3KEFA/glassfish5/glassfish/modules/javax.security.auth.message-api.jar (/home/jenkins/workspace/jakartaee-tck_master-M5QQ24N5SVVYX5KB3WEGZPMN4DNYF7IYAKOEXU5EKNOPHEJ3KEFA/glassfish5/glassfish/modules/javax.security.auth.message-api.jar (No such file or directory)). This directory or jar file will be ignored!
[javatest.batch] Warning: incorrect classpath parameter: /home/jenkins/workspace/jakartaee-tck_master-M5QQ24N5SVVYX5KB3WEGZPMN4DNYF7IYAKOEXU5EKNOPHEJ3KEFA/glassfish5/glassfish/modules/endorsed/javax.annotation-api.jar (/home/jenkins/workspace/jakartaee-tck_master-M5QQ24N5SVVYX5KB3WEGZPMN4DNYF7IYAKOEXU5EKNOPHEJ3KEFA/glassfish5/glassfish/modules/endorsed/javax.annotation-api.jar (No such file or directory)). This directory or jar file will be ignored!
[javatest.batch] Warning: incorrect classpath parameter: /home/jenkins/workspace/jakartaee-tck_master-M5QQ24N5SVVYX5KB3WEGZPMN4DNYF7IYAKOEXU5EKNOPHEJ3KEFA/glassfish5/glassfish/modules/javax.inject.jar (/home/jenkins/workspace/jakartaee-tck_master-M5QQ24N5SVVYX5KB3WEGZPMN4DNYF7IYAKOEXU5EKNOPHEJ3KEFA/glassfish5/glassfish/modules/javax.inject.jar (No such file or directory)). This directory or jar file will be ignored!
[javatest.batch] Warning: incorrect classpath parameter: /home/jenkins/workspace/jakartaee-tck_master-M5QQ24N5SVVYX5KB3WEGZPMN4DNYF7IYAKOEXU5EKNOPHEJ3KEFA/glassfish5/glassfish/modules/javax.faces.jar (/home/jenkins/workspace/jakartaee-tck_master-M5QQ24N5SVVYX5KB3WEGZPMN4DNYF7IYAKOEXU5EKNOPHEJ3KEFA/glassfish5/glassfish/modules/javax.faces.jar (No such file or directory)). This directory or jar file will be ignored!
[javatest.batch] Warning: incorrect classpath parameter: /home/jenkins/workspace/jakartaee-tck_master-M5QQ24N5SVVYX5KB3WEGZPMN4DNYF7IYAKOEXU5EKNOPHEJ3KEFA/glassfish5/glassfish/modules/javax.interceptor-api.jar (/home/jenkins/workspace/jakartaee-tck_master-M5QQ24N5SVVYX5KB3WEGZPMN4DNYF7IYAKOEXU5EKNOPHEJ3KEFA/glassfish5/glassfish/modules/javax.interceptor-api.jar (No such file or directory)). This directory or jar file will be ignored!
[javatest.batch] Warning: incorrect classpath parameter: /home/jenkins/workspace/jakartaee-tck_master-M5QQ24N5SVVYX5KB3WEGZPMN4DNYF7IYAKOEXU5EKNOPHEJ3KEFA/glassfish5/glassfish/modules/javax.ejb-api.jar (/home/jenkins/workspace/jakartaee-tck_master-M5QQ24N5SVVYX5KB3WEGZPMN4DNYF7IYAKOEXU5EKNOPHEJ3KEFA/glassfish5/glassfish/modules/javax.ejb-api.jar (No such file or directory)). This directory or jar file will be ignored!
[javatest.batch] 
[javatest.batch] Missing Classes
[javatest.batch] ---------------
[javatest.batch] 
[javatest.batch] javax.security.enterprise.authentication.mechanism.http.AuthenticationParameters
[javatest.batch] javax.security.enterprise.authentication.mechanism.http.AutoApplySession
[javatest.batch] javax.security.enterprise.authentication.mechanism.http.BasicAuthenticationMechanismDefinition
[javatest.batch] javax.security.enterprise.authentication.mechanism.http.CustomFormAuthenticationMechanismDefinition
[javatest.batch] javax.security.enterprise.authentication.mechanism.http.FormAuthenticationMechanismDefinition
[javatest.batch] javax.security.enterprise.authentication.mechanism.http.HttpAuthenticationMechanism
[javatest.batch] javax.security.enterprise.authentication.mechanism.http.HttpMessageContext
[javatest.batch] javax.security.enterprise.authentication.mechanism.http.HttpMessageContextWrapper
[javatest.batch] javax.security.enterprise.authentication.mechanism.http.LoginToContinue
[javatest.batch] javax.security.enterprise.authentication.mechanism.http.RememberMe
[javatest.batch] 
[javatest.batch] 
[javatest.batch] 
[javatest.batch] 12-08-2018 07:47:35:  ********** Package 'javax.security.enterprise.authentication.mechanism.http' - FAILED (REFLECTION MODE) **********
[javatest.batch] 12-08-2018 07:47:35:  ********** END VALIDATE PACKAGE 'javax.security.enterprise.authentication.mechanism.http' **********
```

As a first thought, can it be related with the renaming of the jars from javax to jakarta?

**Comment by anajosep** [comment]
I was running the JakartaEE TCK. For Standalone TCK, my latest change, https://github.com/eclipse-ee4j/jakartaee-tck/commit/f025cc4aae20221f376243a81498008822c5a00f
would fix the classpaths for javax.*.jar -> jakarta.*.jar renaming.

**Comment by arjantijms** [comment]
This large amount of failures is very unlikely to be caused by anything in the code of either Soteria or the API, especially since basically no changes to code have been made there since the donation.

See: https://github.com/eclipse-ee4j/soteria/commits/EE4J_8

If I take a look at the first failure, it's a 404, meaning that indeed what @ggam asserts that deployments are failing is not unreasonable to surmise:

https://jenkins.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/154/testReport/junit/com.sun.ts.tests.securityapi.ham.autoapplysession/Client/testAutoApplySession/

**Comment by ggam** [comment]
@anajosep I've rerun (standalone) locally with latest GlassFish from Jenkins and I have only 2 failed tests, both EJB related. Any chance you could force a standalone build from Jenkins to see if there are any differences? I haven't managed to make the full CTS run on my machine.

**Comment by anajosep** [comment]
@ggam https://jenkins.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/154/
 This run was actually a standalone run with latest TCK code base against GF version
Git Branch: EE4J_8
Build date: Sat Dec  8 00:15:45 UTC 2018

I see CDI related warnings in the GF server logs.

`
[2018-12-08T13:12:05.132+0000] [glassfish 5.0] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=79 _ThreadName=AutoDeployer] [timeMillis: 1544274725132] [levelValue: 1000] [[
  Exception while loading the app : CDI deployment failure:WELD-001408: Unsatisfied dependencies for type IdentityStoreHandler with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private com.sun.ts.tests.securityapi.ham.sam.delegation.TestAuthenticationMechanism.identityStoreHandler
  at com.sun.ts.tests.securityapi.ham.sam.delegation.TestAuthenticationMechanism.identityStoreHandler(TestAuthenticationMechanism.java:0)
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type IdentityStoreHandler with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private com.sun.ts.tests.securityapi.ham.sam.delegation.TestAuthenticationMechanism.identityStoreHandler
  at com.sun.ts.tests.securityapi.ham.sam.delegation.TestAuthenticationMechanism.identityStoreHandler(TestAuthenticationMechanism.java:0)

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:375)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:287)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:140)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:161)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:518)
	at org.jboss.weld.bootstrap.Validator.validateBeans(Validator.java:504)
	at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:479)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:481)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
	at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:206)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:107)
`
Any idea what can be causing this Exception.

**Comment by ggam** [comment]
I'm now able to reproduce the problem locally. The same WAR that GlassFish does not deploy is accepted by Payara. Let me dig a bit deeper.

**Comment by ggam** [comment]
@anajosep I have created the simplest possible application that injects the SecurityContext, with just one single class:
```
package eu.ggam.mavenproject2;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.security.enterprise.SecurityContext;

@ApplicationScoped
public class TestBean {

    @Inject
    private SecurityContext sc;
}

```

This fails to deploy on GlassFish EE4J_8 with your same error, but works as expected on Payara.

**Comment by jigneshbhodia** [comment]
Just one comment, are we using right updated version of JDK 1.8?  I see that current used is JDK1.8_u171. Do we want to use JDK1.8_u191 ?

**Comment by m0mus** [comment]
@keilw no, we are using Oracle JDK for testing

**Comment by m0mus** [comment]
Update from @yaminikb:

I looked at the issue and it seems to indicate that Soteria is not loading. I remember we had soteria tests included in security dev tests. I can’t seem to locate the job which runs all our CI tests, I don’t know where to look.

@vinayvishal, please check following:

1. Bring up GlassFish locally and validate if Soteria is loading or not. (try some sample app)
2. Check the state of Soteria dev tests.
3. Try running JSR 375 TCK locally (you should be already familiar with this).

**Comment by vinayvishal** [comment]
The root cause for this has been identified.
`META-INF/services` folder, which is to provide details of service provide by way of having provider-configuration file, is missing from the staged Soteria [release](https://oss.sonatype.org/content/groups/staging/org/glassfish/soteria/jakarta.security.enterprise/1.0.1/).

This folder contains following two files providing details of service providers.

```
.
└── services
    ├── javax.enterprise.inject.spi.Extension
    └── javax.servlet.ServletContainerInitializer
```
`org.glassfish.soteria.cdi.CdiExtension` which is listed in `javax.enterprise.inject.spi.Extension` activates `javax.security.enterprise.authentication.mechanism.http.BasicAuthenticationMechanismDefinition` and ` javax.servlet.ServletContainerInitializer` points to `org.glassfish.soteria.servlet.SamRegistrationInstaller`. Since `services` directory itself is missing, the applications are not working as expected.

Soteria need to be re-released to have the `META-INF/services` directory with these provider configuration file. 

Locally I tested with modified soteria jar and sample application worked as expected.

**Comment by m0mus** [comment]
@arjantijms @ggam Please give a priority to this fix. I am also suggesting to make it properly. I mean fix it, bump Soteria version, release it to staging and reintegrate to GF.

**Comment by arjantijms** [comment]
@m0mus Addressed in https://github.com/eclipse-ee4j/soteria/pull/244

**Comment by arjantijms** [comment]
@m0mus @ggam and others. Soteria can currently not be staged anymore, as Nexus plainly refuses it. I've created the following bug for this:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=543346

**Comment by m0mus** [comment]
Sonatype issue is filled:
https://issues.sonatype.org/browse/MVNCENTRAL-4395

**Comment by arjantijms** [comment]
Sonetype tweaked something over at their side, and after that the script worked again:

https://oss.sonatype.org/content/repositories/staging/org/glassfish/soteria/jakarta.security.enterprise/1.0.1/

**Comment by m0mus** [comment]
We have a green CTS run. Closing this issue. Security API and Soteria can be released to Maven Central.
