### ISSUE TITLE
Update Scope Statement for Jakarta Security Project

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/security-api#117]
Update the scope statement for the project: https://projects.eclipse.org/projects/ee4j.jakartaee-platform/governance

See https://docs.google.com/spreadsheets/d/1FPLjo_DJDOQngVtdrYgaDk98d9NBG-0ODgdmOG3LOsI/edit?usp=sharing for examples.

**Comment by gilbertoca** [comment]
I think **Jakarta Security**  would be a better name, no?
And the scope could be (taken form here https://javaee.github.io/security-spec/ )
_This specification will holistically attempt to simplify, standardize, and modernize the Security API across the platform in areas identified by the community._

**Comment by ggam** [comment]
+1 for Jakarta Security

**Comment by smillidge** [comment]
@arjantijms can you lead finalising the scope statement and move the issue over to the "Ready for Review..." column in the project.

**Comment by waynebeaton** [comment]
> This specification will holistically attempt to simplify, standardize, and modernize the Security API across the platform in areas identified by the community.

Words like "attempt" do not belong in a scope statement and words like "modernize" suggest that work is point-in-time (which makes sense in the context of a JSR, but not in the context of the specification itself). Terms like "areas identified by the community" are too open ended. We need a scope statement that tells us what the specification defines.

**Comment by ivargrimstad** [comment]
> Jakarta Security defines a standard for creating secure Jakarta EE applications in modern application paradigms.
