### ISSUE TITLE
Change project name to Jakarta Security

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/security-api#118]
Background information:
https://waynebeaton.wordpress.com/2019/04/04/renaming-java-ee-specifications-for-jakarta-ee/

Checklist:
- [x]  GitHub
- [x]  README file
- [x]  CONTRIBUTING file
- [x]  Eclipse Project under https://projects.eclipse.org/projects/ee4j

**Comment by keilw** [comment]
@ivargrimstad @arjantijms What about the `groupId`?
It's currently `jakarta.security.enterprise`, if the "Enterprise" is dropped and it's simply called "Jakarta Security", then maybe we should shorten that to "jakarta.security" as well. There is no more conflict with "javax.security" as this spec evolves.

**Comment by ivargrimstad** [comment]
@keilw Yes, that would make sense. But most likely for a later version as Jakarta EE 8 will use the same artifacts as for the Java EE 8 version built in January.

**Comment by keilw** [comment]
@ivargrimstad I was thinking more about 9, but should the whole name change affect 8 already while packages and other namespaces only change afterwards?

**Comment by ggam** [comment]
I expected preserving the package name even if the spec is renamed, unless
there's a general plan to rename them tl jakarta on all specs

**Comment by ivargrimstad** [comment]
Name changes will be made for the Jakarta EE 8 release. Everything else will remain the same.

**Comment by keilw** [comment]
@ggam In Jakarta EE 8, after that package names have to change and most specs that are active expect to change all of it, not split e.g. into `javax.security.enterprise` for Java/Jakarta EE 8 state of the code and `jakarta.security` for new elements.

**Comment by ggam** [comment]
AFAIK the trademark agreement Eclipse is pursuing, would allow expansion of
packages under the current namespaces.

**Comment by keilw** [comment]
It seems your information could be outdated. Updating anything looks like renaming is inevitable. So far the only ones that might keep their packages as they are would be "legacy" specs e.g. something that never gets touched again.

**Comment by ggam** [comment]
I had no idea. Has this been published somewhere already?

**Comment by gilbertoca** [comment]
@ggam you will find more info here https://eclipse-foundation.blog/2019/05/03/jakarta-ee-java-trademarks/
