### ISSUE TITLE
Prepare Jakarta Security for Jakarta EE 8 Release

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/security-api#124]
### Instructions

- [x] Update text files
- [x] Generate "boilerplate" specification project
- [x] Make a staging release
- [x] Generate Stand-alone TCK test results
- [x] Create a PR to jakartaee/specifications repository
- [x] Update the Jakarta EE API jar by submitting a PR to the [jakartaee-api](https://github.com/eclipse-ee4j/jakartaee-api) project

See [here](https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release) for detailed instructions.

**Comment by arjantijms** [comment]
Staging release done: https://oss.sonatype.org/content/repositories/staging/jakarta/security/enterprise/jakarta.security.enterprise-api/1.0.2/

**Comment by arjantijms** [comment]
TCK results done: [summary.txt](https://jenkins.eclipse.org/es/job/2_security-run-tck-against-staged-build/lastSuccessfulBuild/artifact/securityapitck/bin/summary.txt/*view*/)

**Comment by arjantijms** [comment]
* [Spec PR 1](https://github.com/jakartaee/specifications/pull/42)
* [Spec PR 2](https://github.com/jakartaee/specifications/pull/43)

**Comment by bshannon** [comment]
@arjantijms The TCK summary will need to be published someplace with more long term
stability than Jenkins job results. Also, the Spec Committee has decided that only the
top lines with totals need to be published, although you're free to publish more if you want.

**Comment by arjantijms** [comment]
@bshannon I agree, I put the link there as a quick hint. For now I've also included the results in the PR:

https://github.com/jakartaee/specifications/blob/fe081a518bf1b4dcc6807992d241dfae20d95fc2/security/1.0/tck_results_summary.txt

**Comment by bshannon** [comment]
@arjantijms I think we decided *not* to publish the TCK results on the spec pages, but to
keep them on some project/product-specific page.  For example, I put the Jakarta Mail
TCK results on the [Jakarta Mail web site](https://eclipse-ee4j.github.io/javamail/TCK-Results.html).

**Comment by arjantijms** [comment]
@bshannon For now I basically followed @m0mus 's lead: 

https://github.com/jakartaee/specifications/blob/aba76c7a0f2e7fb05740ca00ff4d64686139add2/jsonp/1.1/tck_results_summary.txt

I can of course remove those files and publish them elsewhere later.

**Comment by bshannon** [comment]
@arjantijms And when I finally catch up on all the PR reviewing I need to do, I'll put these comments there as well.  :-)

**Comment by m0mus** [comment]
Reopening because new tasks were added.

**Comment by arjantijms** [comment]
[API PR](https://github.com/eclipse-ee4j/jakartaee-api/pull/16)

**Comment by arjantijms** [comment]
[Github pages requested](https://bugs.eclipse.org/bugs/show_bug.cgi?id=549721)

**Comment by arjantijms** [comment]
[Github pages for implementation](https://eclipse-ee4j.github.io/soteria/)
