### ISSUE TITLE
Deliver security-api Specification Version update for Jakarta EE 9

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/security-api#156]
**Is your feature request related to a problem? Please describe.**
Jakarta EE 9 is the next major release, with the main focus of moving from the ```javax``` namespace to the ```jakarta``` namespace.

**Describe the solution you'd like**
This issue will be used to track the progress of this work effort via the [Jakarta EE 9 Project board](https://github.com/orgs/eclipse-ee4j/projects/17).

**Additional context**
[Jakarta EE Specification Process](https://jakarta.ee/about/jesp/)
[Eclipse Project Handbook](https://www.eclipse.org/projects/handbook/#release)
[Eclipse Release Record for Jakarta EE 9](https://projects.eclipse.org/projects/ee4j.jakartaee-platform/releases/9)

**ToDo**
- [x] **[Create Eclipse Release Record](https://www.eclipse.org/projects/handbook/#pmi-commands-release) in your respective Jakarta Specification Project.**
 Most Component Release Records will just reference the [Jakarta EE 9 Platform Release Plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan).  But, if your Component deviates at all from the Platform Release Plan, then a description of the changes will be required in the Release Record.
- [x] **Initiate a ballot for your Jakarta Release Record/Plan.**
 Again, if your component is only doing the required minimum as defined by the [Jakarta EE 9 Platform Release Plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan), then no separate ballot is required.  You are already approved.  But, if your component deviates from the Platform Release Plan, then you will need to initiate your own ballot as defined by the [Jakarta EE Specification Process](https://jakarta.ee/about/jesp/).
- [x] **Jakarta-ize your Specification document (if applicable)**
 Many of the Jakarta EE components now have the source for their Specification documents.  It is strongly recommended that these Specification documents are properly updated to represent Jakarta EE instead of Java EE.  Some [helpful instructions are documented](https://github.com/jakartaee/specification-committee/blob/master/steps_javaee_to_jakartaee.adoc) here.
- [x] **javax -> jakarta Spec updates**
 If your component has Specification source, then all javax package references need to be updated to use jakarta package references.
- [x] **javax -> jakarta API updates**
 Your component APIs need to move from using the javax namespace to using the jakarta namespace.
- [x] **Release Candidate (RC) of Jakarta API in Maven Central**
 A Release Candidate of your component API should be pushed to Maven Central as soon as humanly possible.  This will allow other dependent components to utilize your APIs as they are updating their APIs.  Multiple revisions of these Release Candidate APIs are allowed (and probably expected) during the development cycle.
- [x] **javax -> jakarta TCK updates**
 Your component TCK needs to be updated to use the jakarta namespace.
- [x] **javax -> jakarta Compatible Implementation updates**
 Your compatible implementation that will be used to demonstrate completeness of the Specification needs to be updated to use the jakarta namespace.
- [x] **Final Jakarta API available in Staging Repo**
 When ready, your final version of the API needs to be staged to get ready for the PR review and approvals.
- [x] **Draft Specification and Apidoc PRs ready for review**
 Like we did for Jakarta EE 8, draft PRs need to be created and reviewed in preparation for the final ballots.
- [x] **Release Review Ballot started**
 Each Jakarta EE component will need to initiate a separate Release Review ballot after proper reviewing has completed.  To be clear, there will not be a blanket Release Review for all of Jakarta EE 9 like we did for the Plan Review.  Each component needs a separate Release Review.

**Comment by kwsutter** [comment]
Can I ask this team to please create and assign the following labels to this Issue?  Thank you!
[Epic]
[wave:6]

**Comment by kwsutter** [comment]
Jakarta Security 2.0 [Release Record](https://projects.eclipse.org/projects/ee4j.es/releases/2.0/plan).

**Comment by keilw** [comment]
Happy to help with the refactoring.

**Comment by mbroz2** [comment]
@keilw if it helps, I do have a commit that updates both javax to jakarta for both the spec and API (here: https://github.com/mbroz2/security-api/commit/26781f596e9bbd60d7bb58b099f038ef55e562e8), but I've been sitting on it as I was trying to investigate what the dictionary.txt (https://github.com/eclipse-ee4j/security-api/blob/master/spec/src/main/asciidoc/dictionary.txt) is used for and how it should be updated regarding javax->jakarta
In the commit, I did replace javax with jakarta, but again, not sure if that's the correct thing to do as I can't find any references to that file and I've never seen a dictionary being used with asciidoc (though perhaps it's for something else like javadoc)

**Comment by arjantijms** [comment]
Soteria has been updated in https://github.com/eclipse-ee4j/soteria/pull/267

But waiting for Jakarta implementation versions of GlassFish Servlet, Weld, etc to actually run this.

**Comment by arjantijms** [comment]
RC2 of the API: https://repo1.maven.org/maven2/jakarta/security/enterprise/jakarta.security.enterprise-api/2.0.0-RC2/

**Comment by OndroMih** [comment]
From the comments and the source code I assume that the spec is (almost?) Jakarta-ized, the API is migrated to the jakarta.* namespace and the Soteria impl is also migrated to the jakarta.* namespace. Maybe we can update the particular bullet points and move it further right on the Jakarta EE 9 project board? // @arjantijms @rdebusscher @m0mus

**Comment by arjantijms** [comment]
@OndroMih I just updated them, seems we missed them indeed. The spec document was converted a while ago, as was the release of the API.

**Comment by arjantijms** [comment]
Jakartified TCK: https://github.com/eclipse-ee4j/jakartaee-tck/commit/d80fa31c3d0200c263faebc2626f8f053ab87601

**Comment by arjantijms** [comment]
Jakartified implementation: https://github.com/eclipse-ee4j/soteria/commit/79fb251a40f8da42e70764b11f0f8f82c562e928

**Comment by kwsutter** [comment]
One last request for the Specifications PR to promote the Milestone deliverables for this Project.  The PR is created against the [Jakarta EE specifications github repo](https://github.com/jakartaee/specifications/pulls).  A template is automatically used when creating PRs against this repo which should help with understanding the steps required for a successful merge.  We're not looking for perfection for this Milestone.  We just want the ability to promote the great work that all of the Projects are doing.

If you submit a PR, please feel free to move this Epic to the [Milestone 1 Ready column in the Project Board](https://github.com/orgs/eclipse-ee4j/projects/17#column-9442495).  Thanks!

**Comment by arjantijms** [comment]
Release bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=568097

**Comment by arjantijms** [comment]
Release is done. Thanks to all who helped!
