### ISSUE TITLE
Weird code formatting

### ISSUE THREAD

**Issue by vsmid** [eclipse-ee4j/security-api#167]
There is something weird in how code is formatted in api module.

**Comment by arjantijms** [comment]
Do you know what is weird? (or bad)

**Comment by vsmid** [comment]
e.g. [SecurityContext](https://github.com/eclipse-ee4j/security-api/blob/master/api/src/main/java/jakarta/security/enterprise/SecurityContext.java)

**Comment by arjantijms** [comment]
I see, tabs have entered the code. I many IDEs this is hard to see, but on GitHub it's obvious. Thx!

**Comment by arjantijms** [comment]
@vsmid It's now fixed, thanks again!
