### ISSUE TITLE
Compatibility certification request for Jakarta Security 2.0

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/security-api#177]
- [x] Organization Name ("Organization") and, if applicable, URL\
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)\
  [Eclipse Soteria 2.0.0](https://github.com/eclipse-ee4j/soteria/releases/download/2.0.0-M3-RELEASE/jakarta.security.enterprise-2.0.0-M3.jar)
- [x] Specification Name, Version and download URL\
   [Jakarta Security 2.0](https://jakarta.ee/specifications/security/2.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL\
  [Jakarta Security TCK 2.0.0](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-security-tck-2.0.0.zip), SHA-256: `63563b05a7b09d7d840395570f4466e129026dfd071bd037ef159a9f817bf338`
- [x] Public URL of TCK Results Summary\
  [TCK results summary](https://eclipse-ee4j.github.io/soteria/certifications/jakarta-security/2.0/TCK-Results)
- [x] Any Additional Specification Certification Requirements\
  None
- [x] Java runtime used to run the implementation\
  Oracle JDK 1.8.0_202
- [x] Summary of the information for the certification environment, operating system, cloud, ...\
  Alpine Linux v3.12
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by edbratt** [comment]
Should this TCK summary page be included with GlassFish, or Soteria? Ultimately, I think either is fine, but it may be more clear if the TCK summary was included with Soteria. Soteria is the CI and we want to be clear about that.

**Comment by arjantijms** [comment]
I wasn't really sure about that indeed. I noticed for the previous version it was done for both GlassFish and Soteria. I just did the PR for GlassFish here, but I can copy it to the Soteria site too: https://github.com/eclipse-ee4j/glassfish/pull/23228

**Comment by arjantijms** [comment]
@edbratt TCK results now hosted at https://eclipse-ee4j.github.io/soteria/certifications/jakarta-security/2.0/TCK-Results and link in description adjusted.

**Comment by edbratt** [comment]
Please update the [TCK summary](https://eclipse-ee4j.github.io/soteria/certifications/jakarta-security/2.0/TCK-Results) to point to the TCK that exists in the Jakarta EE 9 Promoted directory (e.g. [here](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-security-tck-2.0.0.zip)). These will not be removed whereas the staged copies are considered volatile. If you want to list both the Promoted and final TCK download links, that's okay, but the summary should always have a valid link, even if it's published before the Spec. is final (otherwise, it's impossible to verify before the Spec. is final. This is only an issue for pre-ballot certification requests.)

I would also recommend this certification request issue refer to the promoted TCK as well (for the same reason).

**Comment by arjantijms** [comment]
> Please update the TCK summary to point to the TCK that exists in the Jakarta EE 9 Promoted directory

Done. I know included both links.

> I would also recommend this certification request issue refer to the promoted TCK as well (for the same reason).

Done

**Comment by edbratt** [comment]
Excellent! Thank you!

**Comment by edbratt** [comment]
+1 on the certification request

**Comment by jeanouii** [comment]
I cannot approve it for now but looks good.

**Comment by jeanouii** [comment]
Once marked approved, please complete this last step

> The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.

**Comment by arjantijms** [comment]
@jeanouii I'll approve it, thanks for mentioning it.

**Comment by arjantijms** [comment]
As project of Jakarta Security I assert this can be approved and closed.
