### ISSUE TITLE
Jakarta Security 2.0 Release Review - Completion Steps

### ISSUE THREAD

**Issue by jeanouii** [eclipse-ee4j/security-api#181]
- [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [x] approve the compatibility request.
 - [x] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by jeanouii** [comment]
I'll complete this list of things when I have commit access granted.

**Comment by arjantijms** [comment]
@jeanouii Note that step 1 is waiting for the release review to complete. 

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=568097

**Comment by arjantijms** [comment]
Release review completed. @jeanouii I promoted to Maven Central as it seems you don't have the rights yet, but the ballot for it should start soon, so with the next release you should be able to do it too.

**Comment by arjantijms** [comment]
Final jars available at: https://repo1.maven.org/maven2/jakarta/security/enterprise/jakarta.security.enterprise-api/2.0.0/
