### ISSUE TITLE
To all committers: subscribing to the project's mailing list

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/security-api#81]
Hi,

The Eclipse Enterprise Security ("es") project has a mailing list that we all should use for discussions involving EE Security. However, at the moment nobody has subscribed yet.

Subscription can be done here:

https://accounts.eclipse.org/mailing-list/es-dev

* @ggam ✔️
* @keilw ✔️
* @bshannon 
* @edbratt 
* @dblevins 
* @ivargrimstad ✔️
* @liuxiangde 
* @vinayvishal 
* @yaminikb 
* @m0mus 
* @teddyjtorres

**Comment by ggam** [comment]
Subscribed, thanks!

**Comment by ivargrimstad** [comment]
Me too :)

**Comment by keilw** [comment]
I also joined. Not sure, if the checkmarks above are tied to the GitHub user, because that user (like my Eclipse.org or jcp.org user account) is tied to another email address, but I prefer to use Gmail because of its larger mailbox and search.

**Comment by mmotwakel** [comment]
Done

**Comment by ggam** [comment]
Ping @eclipse-ee4j/eclipse-es. The list still has only 7 subcribers. 

Btw, I've already started a thread: http://dev.eclipse.org/mhonarc/lists/es-dev/msg00003.html

**Comment by m-reza-rahman** [comment]
Subscribed. It will be a while before I can legitimately claim to be a committer.

**Comment by arjantijms** [comment]
@m-reza-rahman Thanks!

The EE Security API has several contributions of you in it via the ideas you expressed in the various issues you created back then ;)
