### ISSUE TITLE
Provide literals for built-in annotations

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/security-api#82]
Since CDI 2.0, CDI provides annotation literals for many of its annotations (see https://issues.jboss.org/browse/CDI-485). 

Just as the built-in CDI annotations,  EE Security annotation literals are also being implemented by projects. As a public example, see https://github.com/javaee-samples/javaee8-samples/blob/master/security/dynamic-rememberme/src/main/java/org/javaee8/security/dynamic/rememberme/util/RememberMeAnnotationLiteral.java

Literals are useful for looking up bean instances using the bean manager, as well as when applying interceptors dynamically.

**Comment by arjantijms** [comment]
>Why a no-op of() method, wouldn't INSTANCE also work here?

With INSTANCE you'd expect a constant. The CDI examples all use `of()` but with a parameter (since all these only have 1 annotation attribute.

There needs to be something to kickoff the builder. Open to suggestions in a followup PR.

**Comment by arjantijms** [comment]
P.s. an alternative I was playing with is:

```
RememberMe literal = RememberMe.Literal.of(
    cookieMaxAgeSeconds(100),
    cookieSecureOnly(false),
    cookieHttpOnly(false)
 );
```

Where `cookieMaxAgeSeconds` etc are statically imported methods that return a `NamedParameter` instance. The `of()` method is a varargs method exception these. It's roughly like how the Java SE 8 stream method `collect()` works.

It reads a bit nicer, but you'd have to import these methods, which may be a bit less self-discovery than chaining builders calls.

Thoughts?

**Comment by keilw** [comment]
I'll propose something along the lines of
```java
RememberMe literal = RememberMe.Literal.builder()
                                       .cookieMaxAgeSeconds(100)
                                       .cookieSecureOnly(false)
                                       .cookieHttpOnly(false)
                                       .build();
```

As the method does not return `Literal` itself, but the `LiteralBuilder`. And look at `Optional` and all other cases I know, `of()`, `valueOf()` or `instanceOf()` always return the exact class they're applied on, not a builder.
