### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/security-api#88]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by keilw** [comment]
What is the plan for the number of Jenkins instances?
E.g. MicroProfile is just a single Eclipse project, hence it also got one Jenkins https://ci.eclipse.org/microprofile/ despite dozens of GitHub repos. 

This project is a dedicated EE4J project: https://projects.eclipse.org/projects/ee4j.es
Similar for Soteria: https://projects.eclipse.org/projects/ee4j.soteria
So is the plan to have a Jenkins instance for each, or should there be one for Security?
EE4J already has a Jenkins instance: https://ci.eclipse.org/ee4j/
Hard do say, what the plans are for multiple EE4J projects, maybe that's for the Jakarta EE Profiles, TCK, etc.?

I saw the JSON-P pipeline and can also log into that Jenkins instance. 
JSONP has just one repository for API and RI/SI (as it should be called here in the future) while JSONB and Yasson are two separate projects, too. 

Does the "Build after a SNAPSHOT dependency was built" build Soteria whenever a new SNAPSHOT of this API was built and deployed to a SNAPSHOT repository?

**Comment by m0mus** [comment]
There is one Jenkins instance per project. So, Security and Soteria have different Jenkins instances. How projects committers define and design jobs is totally up them.

**Comment by ggam** [comment]
Yes, that's the list and is open for everyone and already meeting an
posting meeting minutes. Not sure who can join the meetings but you being a
member of various committees shouldn't find too much problems.

**Comment by keilw** [comment]
Then I'll try to subscribe the list at least (that unless it's a private group for certain people should be possible) can't promise about the calls, but if it does not clash with other meetings I have I might also join that if possible.

**Comment by m0mus** [comment]
@keilw yes, ee4j-build is a mailing list for build related topics. We also have weekly status meetings.

**Comment by keilw** [comment]
@m0mus I joined the mailing list, if the status call is not too early (CET) or conflicts e.g. with the Spec Committee call, I'd be happy to join it if possible.

**Comment by keilw** [comment]
I have not tried it here or in the other repos, but can either committer ask for a JIPP (Jenkins Per Project) with Bugzilla?

**Comment by m0mus** [comment]
Feel free to ask, describe the situation, add me to CC in the bug. I was talking with @eclipsewebmaster  couple of weeks ago and we agreed that it's solvable. 
They said that another solution is using Cloud Jenkins. In this case jobs descriptions are a part of repository. I don't know the details. @eclipsewebmaster, can you help here?

**Comment by ggam** [comment]
anyone started working on this? I might try to do it if all other committers are too busy.

**Comment by ggam** [comment]
The Jenkins instance will be available today within some hours: https://bugs.eclipse.org/bugs/show_bug.cgi?id=538888

I'm assigning this to myself and I'll work on it within the weekend. We won't be able to release until week 40 (https://docs.google.com/spreadsheets/d/1O2NA6YddYQy34riTabQd_lkNwwFzKq1HevxCJYNXrv4/edit#gid=0) but work can start for builds.

**Comment by m0mus** [comment]
Update from @arjantijms:
```
Two jobs created. 
Simple maven job for master builds - succeeds
Release job based on shell script and using secret files; only initial setup
```
Closing this task as completed based on the status above.
