### ISSUE TITLE
Release CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/security-api#89]
We need to create a release CI/CD pipeline for this project. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)
- [Release job on the new cloud infra](https://wiki.eclipse.org/JakartaEE_New_Infra_Release_Job)

**Comment by m0mus** [comment]
Update from @arjantijms:
```
Release job based on shell script and using secret files; only initial setup
```

**Comment by arjantijms** [comment]
Job fully done, and fully runs. https://github.com/eclipse-ee4j/security-api/tree/1.0.1 created by eclipse bot.

**Comment by senivam** [comment]
@arjantijms could you please provide a link to that job?

**Comment by arjantijms** [comment]
@senivam that's the one indeed
